[application]
name = "opti-z-oignons"

[web.app]
title = "Optz"
base_path = "opti-z-oignons"

[web.resource]

[web.resource.dev]

[bundle]
publisher = "AntoinePrv"
short_description = "Table placement optimization interface"
