[project]
name = "table-assignment"
version = "0.0.1"
description = "Assign people to table with preferences"
authors = ["AntoinePrv <AntoinePrv@users.noreply.github.com>"]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[environments]
default = { features = ["build", "css"], solve-group = "default" }
dev = { features = ["build", "css", "test", "dev"], solve-group = "default" }

[feature.build.dependencies]
sccache = ">=0.8.1"
c-compiler = ">=1.7.0,<2"
rust = ">=1.85.0"
rust-std-wasm32-unknown-unknown = ">=1.83.0"

[feature.css.dependencies]
nodejs = "*"

[feature.css.tasks.npm]
cmd = "npm"
[feature.css.tasks.init-tailwind]
cmd = "npm install tailwindcss @tailwindcss/cli"
inputs = ["package.json", "package-lock.json"]
outputs = ["node_modules/"]
[feature.css.tasks.tailwind]
cmd = "npx tailwindcss"
depends-on = ["init-tailwind"]

[feature.build.activation.env]
RUSTC_WRAPPER = "sccache"

[feature.test.dependencies]
pre-commit = ">=3.7.1"
taplo = ">=0.9.2"

[feature.test.tasks]
# Formatters
fmt-cargo = "cargo fmt"
fmt-taplo = "taplo fmt"
fmt-dx = "dx fmt"
fmt = { depends-on = ["fmt-taplo", "fmt-cargo", "fmt-dx"] }
# Checkers
check-cargo = "cargo check --all-targets --workspace"
check-clippy = { cmd = "cargo --locked clippy --fix --allow-staged", env = { RUSTFLAGS = "-Dwarnings", CARGO_TARGET_DIR = "$PIXI_PROJECT_ROOT/target/clippy" } }
check = { depends-on = ["check-cargo", "check-clippy"] }
# Tests
test-cargo = "cargo --locked test --workspace"
test = { depends-on = ["test-cargo"] }
# Pre-commit easy alias
pre-commit = "pre-commit"
pre-commit-all = "pre-commit run --all-files"
# Alias for what is being run in ci (pre-commit runs checks and formatter)
ci = { depends-on = ["pre-commit-all"] }

[feature.dev.dependencies]
rust-src = ">=1.79.0"
sccache = ">=0.8.1"
dioxus = ">=0.6.3"
watchexec = ">=2.2.0,<3"

[feature.dev.tasks]
cargo = "cargo"
dx = "dx"
watch-fmt-dx = "watchexec -e rs dx fmt"
serve-dx = "dx serve"
serve-tailwind = { depends-on = ["init-tailwind"], cmd = """
npx tailwindcss --input ./assets/main.tw.css --output ./assets/main.css --watch
""" }

[feature.dev.activation.env]
RUSTC_WRAPPER = "sccache"
