name: Test and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.0
          cache: true
          manifest-path: pixi.toml
      - name: Run checks through pre-commit
        run: pixi run pre-commit-all
      - name: Run cargo tests
        run: pixi run test-cargo

  build:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.0
          cache: true
          manifest-path: pixi.toml
      - name: Build website
        run: pixi run build-dx
      - name: Save website bundle
        uses: actions/upload-artifact@v4
        with:
          name: public-folder
          path: public/

  deploy:
    needs: ["build"]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/download-artifact@v4
        with:
          name: public-folder
          path: public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
